### PR TITLE
use didInsertElement hook directly

### PR DESCRIPTION
**Pull request by koriroys**

### CODE REVIEW

**Comment by wecc** [comment]
Hey @koriroys, thanks for the proposal! I'm a bit unsure about merging this since I usually recommend using `.on('didInsertElement')` instead of overriding the `didInsertElement` method directly (same thing with `init`). The reason for this is that you don't have to worry about calling super to make sure you're not breaking parent behavior depending on these methods when extending.

Also, `this.$('.modal')` is scoped to the current view/component while `Ember.$('.modal')` would match all elements with `class="modal"` in the document, and we don't want that.

**Comment by koriroys** [comment]
Ok, you can delete the request. Mostly just wanted to see what you thought about it. Thanks for the quick response.

-Kori Roys
@koriroys
koriroys.com

**Comment by koriroys** [comment]
Btw, do you have a link discussing using 'on' vs the ember hooks? I'm fuzzy on why one is better than another. Just haven't run into the downsides of either yet I suppose.

-Kori Roys
@koriroys
koriroys.com

**Comment by wecc** [comment]
@koriroys Got it! I think [this blog post](http://reefpoints.dockyard.com/2014/04/28/dont-override-init.html) explains it quite nicely.

**Comment by koriroys** [comment]
Looks like there is some debate about it: https://github.com/emberjs/ember.js/pull/10198

**Comment by wecc** [comment]
Yeah, for sure. Very interesting!

**Pull request closed without merging**
